import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from './LoginBtn.js'
import LogoutBtn from './LogoutBtn.js'
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  let session = await getServerSession(authOptions) // 서버컴포넌트, 서버기능안에서 사용가능

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="navbar"> 
          <Link href="/" className="logo">Main</Link> 
          <Link href="/projects">Projects</Link> 
          <Link href="/contact">Contact</Link> 
        </div> */}
        <div className="navbar flex items-center justify-between p-4 bg-gray-800 text-white">
          <div className="flex items-center">
            <Link href="/" className="logo text-xl font-bold">Home</Link>
            <Link href="/projects" className="hover:text-gray-300 ml-4">Projects</Link>
            <Link href="/contact" className="hover:text-gray-300">Contact</Link>
          </div>
          { 
            session 
              ? 
              <span className="flex items-center">
                {session.user.image && (
                  <img src={session.user.image} alt="Profile Image" className="w-8 h-8 rounded-full mr-2" />
                )}
                <span className="mr-2">{session.user.name}</span>
                <LogoutBtn />
              </span>
              : <LoginBtn></LoginBtn>
          }
        </div>
        {children}
      </body>
    </html>
  );
}
